/**
 * Generated by tsnapi — public API snapshot of `state-launcher/headless`
 */
// #region Types
export type StateLauncherCommandSnapshot = Readonly<{
  id: string;
  label?: string;
  description?: string;
  tags: readonly string[];
  routes: readonly StateLauncherRoutePattern[];
  hasLaunchHandler: boolean;
  isActive: boolean;
}>;
export type StateLauncherSnapshot = readonly StateLauncherCommandSnapshot[];
export type StateLauncherSnapshotListener = (_: StateLauncherSnapshot) => void;
// #endregion

// #region Functions
export declare function clearActiveState(): Promise<void>;
export declare function getStateLauncherSnapshot(): StateLauncherSnapshot;
export declare function launchStateLauncherCommand(_: string): Promise<void>;
export declare function subscribeStateLauncher(_: StateLauncherSnapshotListener): () => void;
// #endregion