/**
 * Generated by tsnapi — public API snapshot of `state-launcher`
 */
// #region Types
export type LaunchableStateOptions = {
  label?: string;
  description?: string;
  tags?: string[];
  launch?: LaunchHandler;
};
export type LaunchCleanup = () => void | Promise<void>;
export type LaunchContext = {
  readonly signal: AbortSignal;
};
export type LaunchHandler = (_: LaunchContext) => void | LaunchCleanup | Promise<void | LaunchCleanup>;
export type MountedStateLauncher = {
  unmount(): void;
  open(): void;
  close(): void;
  toggle(): void;
};
export type MountStateLauncherOptions = {
  auth?: StateLauncherAuthOptions;
  target?: HTMLElement;
  initiallyOpen?: boolean;
  position?: 'bottom-right' | 'bottom-left' | 'top-right' | 'top-left';
  title?: string;
};
export type StateLauncherAuthOptions = {
  onSignIn: () => void | Promise<void>;
  onSignOut: () => void | Promise<void>;
};
export type StateLauncherCommand<Id extends string = string> = {
  readonly id: Id;
  readonly label?: string;
  readonly description?: string;
  readonly tags?: readonly string[];
  launch(): Promise<void>;
};
// #endregion

// #region Functions
export declare function clearCommands(): void;
export declare function defineLaunchableState<const Id extends string>(_: Id, _?: LaunchableStateOptions): StateLauncherCommand<Id>;
export declare function launchCommand(_: StateLauncherCommand | string): Promise<void>;
export declare function mountStateLauncher(_?: MountStateLauncherOptions): MountedStateLauncher;
export declare function registerLaunchableState(_: readonly StateLauncherCommand[]): () => void;
export declare function unregisterCommand(_: StateLauncherCommand | string): void;
// #endregion