/**
 * Generated by tsnapi — public API snapshot of `state-launcher`
 */
// #region Types
export type LaunchableStateOptions = {
  label?: string;
  description?: string;
  tags?: string[];
  routes?: readonly StateLauncherRoutePattern[];
  launch?: LaunchHandler;
};
export type LaunchCleanup = () => void | Promise<void>;
export type LaunchContext = {
  readonly signal: AbortSignal;
  defer(_: LaunchCleanup): void;
  signIn(): Promise<void>;
  signOut(): Promise<void>;
};
export type LaunchHandler = (_: LaunchContext) => void | LaunchCleanup | Promise<void | LaunchCleanup>;
export type MountedStateLauncher = {
  unmount(): void;
  refresh(): void;
  open(): void;
  close(): void;
  toggle(): void;
};
export type MountStateLauncherOptions = {
  auth?: StateLauncherAuthOptions;
  target?: HTMLElement;
  initiallyOpen?: boolean;
  position?: 'bottom-right' | 'bottom-left' | 'top-right' | 'top-left';
  showPathname?: boolean;
  title?: string;
};
export type StateLauncherAuthOptions = {
  homePath?: (_: {
    isSignedIn: boolean;
  }) => string;
  isSignedIn: boolean;
  onSignIn: () => void | Promise<void>;
  onSignOut: () => void | Promise<void>;
};
export type StateLauncherCommand<Id extends string = string> = {
  readonly id: Id;
  readonly label?: string;
  readonly description?: string;
  readonly tags?: readonly string[];
  readonly routes?: readonly StateLauncherRoutePattern[];
  launch(): Promise<void>;
};
export type StateLauncherCommandSnapshot = Readonly<{
  id: string;
  label?: string;
  description?: string;
  tags: readonly string[];
  routes: readonly StateLauncherRoutePattern[];
  hasLaunchHandler: boolean;
  isActive: boolean;
}>;
export type StateLauncherRoutePattern = string;
export type StateLauncherSnapshot = readonly StateLauncherCommandSnapshot[];
export type StateLauncherSnapshotListener = (_: StateLauncherSnapshot) => void;
// #endregion

// #region Functions
export declare function clearActiveState(): Promise<void>;
export declare function clearCommands(): void;
export declare function defineLaunchableState<const Id extends string>(_: Id, _?: LaunchableStateOptions): StateLauncherCommand<Id>;
export declare function launchCommand(_: StateLauncherCommand | string): Promise<void>;
export declare function mountStateLauncher(_?: MountStateLauncherOptions): MountedStateLauncher;
export declare function registerLaunchableState(_: readonly StateLauncherCommand[]): () => void;
export declare function unregisterCommand(_: StateLauncherCommand | string): void;
// #endregion