/**
 * Generated by tsnapi — public API snapshot of `state-launcher/preact`
 */
// #region Functions
export declare function useLaunchableState(_: StateLauncherCommand, _: LaunchHandler): void;
// #endregion