/**
 * Generated by tsnapi — public API snapshot of `state-launcher/react`
 */
// #region Types
export type UseLaunchableStateOptions = Omit<LaunchableStateOptions, 'launch'> & {
  launch: LaunchHandler;
};
// #endregion

// #region Functions
export declare function useLaunchableState(_: StateLauncherCommand, _: LaunchHandler): void;
export declare function useLaunchableState<const Id extends string>(_: Id, _: UseLaunchableStateOptions): StateLauncherCommand<Id>;
// #endregion